CREATE TABLE IF NOT EXISTS "wms_tray" (
                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "tray_no" varchar NOT NULL,
                                          "type" int NOT NULL,
                                          "status" int NOT NULL,
                                          "creator" varchar DEFAULT '',
                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          "updater" varchar DEFAULT '',
                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                          PRIMARY KEY ("id")
    ) COMMENT '托盘表';

-- 将该删表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "wms_tray";

-- 将该建表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "wms_secure_invoke_record" (
                                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                          "secure_invoke_json" varchar NOT NULL,
                                                          "status" int NOT NULL,
                                                          "next_retry_time" varchar NOT NULL,
                                                          "retry_times" int NOT NULL,
                                                          "max_retry_times" int NOT NULL,
                                                          "fail_reason" varchar,
                                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                          PRIMARY KEY ("id")
    ) COMMENT '本地消息表';

-- 将该删表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "wms_secure_invoke_record";