CREATE TABLE IF NOT EXISTS "wms_tray" (
                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "tray_no" varchar NOT NULL,
                                          "type" int NOT NULL,
                                          "status" int NOT NULL,
                                          "creator" varchar DEFAULT '',
                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          "updater" varchar DEFAULT '',
                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                          PRIMARY KEY ("id")
    ) COMMENT '托盘表';

-- 将该删表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "wms_tray";